import type { Metadata } from "next";
import "./globals.css";
import UserLayout from "./container/UserLayout";
import AuthProvider from "./AuthProvider";



export const metadata: Metadata = {
  title: "TrippinTrips",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>
          <UserLayout />
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
